config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :potins
  resources :user
end

# Prefix    Verb    URI                                                                                     Controller#
#           POST   /potins(.:format)                                                                        potins#create
# new_potin GET    /potins/new(.:format)                                                                    potins#new

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
    belongs_to :tag
    belongs_to :potin
end

app/models/potin.rb
class Potin < ApplicationRecord
    belongs_to :user
    has_many :tags, through: :gossip_tag
    validates :title, :content, presence: true
end

app/models/relation.rb
class Relation < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :potins, through: :gossip_tag
end

app/models/user.rb
class User < ApplicationRecord
    has_many :potins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @potins = Potin.all
    end
end

app/controllers/potins_controller.rb
class PotinsController < ApplicationController
    def show
        @potins = Potin.find(params[:id])
    end
    def new
        @potin = Potin.new
    end
    def create
        @potin = Potin.new( 'title' => params[:title],
                            'content' => params[:content],
                            'user_id' => params[:user_id])
        if(@potin.save)
            flash.notice = "potin cree"
            redirect_to @potin
        end

    end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/potins_helper.rb
module PotinsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/contact/index.erb
<h1>Contact</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TGP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <script src="https://kit.fontawesome.com/10557b428c.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if notice%>
      <div class="validate">
        <div class="text">
          potin cree
        </div>
        <div class=valid>
          <i class="fas fa-check"></i>
        </div>
      </div>
    <%end%>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.erb
<h1>HOME</h1>

<% @potins.each do |potin| %>
    <div class="potin">
        <div class="title">
            <%= potin.title %>
        </div>
        <div class="content">
            <%= potin.content%>
        </div>
        <div class ="author">
            par : <%= link_to potin.user.first_name, user_path(potin.user) %>
        </div>
        <%= link_to "Voir Potin", potin_path(potin)%>
        </br>
    </div>
<%end%>

app/views/potins/new.html.erb
<%= form_tag url_for(action: 'create'), method: "post" do %>

    <%= label_tag 'Title' %>
    <%= text_field_tag 'title', @potin.title %>
    <br /> <br />
  
    <%= label_tag 'content' %>
    <%= text_area_tag 'content', @potin.content %>
    <br /> <br />
  
    <%= label_tag 'user_id' %>
    <%= text_field_tag 'user_id', @potin.user_id %>
    <br /> <br />
  
    <%= submit_tag 'Create post' %>
  
<% end %>

app/views/potins/show.erb
<%= @potins.title %>

app/views/team/index.erb
<h1>Team</h1>

app/views/user/show.erb
<%= @user.first_name %>
<%= @user.last_name %>